apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logi-resilience.fullname" . }}-frontend
  labels:
    app: {{ include "logi-resilience.name" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ include "logi-resilience.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "logi-resilience.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}-frontend:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
