apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "logi-resilience.fullname" . }}-backend-hpa
  labels:
    {{- include "logi-resilience.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "logi-resilience.fullname" . }}-backend
  minReplicas: {{ .Values.replicaCount.backend }}
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "logi-resilience.fullname" . }}-worker-hpa
  labels:
    {{- include "logi-resilience.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "logi-resilience.fullname" . }}-worker
  minReplicas: {{ .Values.replicaCount.worker | default 2 }}
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
