{
 "title": "Logi-Resilience System Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logi-Resilience Core Operations Telemetry",
   "type": "row",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Request Ingestion Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "HTTP {{method}} {{path}}" }
   ]
  },
  {
   "title": "Avg HTTP Inference & Ingestion Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum / http_request_duration_seconds_count",
     "legendFormat": "Avg Latency {{path}}"
    }
   ]
  },
  {
   "title": "Inference Exceptions (5xx)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status=~\"5.*\"}) or vector(0)",
     "legendFormat": "Internal Server Errors (5xx)"
    }
   ]
  },
  {
   "title": "FastAPI Service Health status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"backend\"}",
     "legendFormat": "Backend Status"
    }
   ]
  },
  {
   "title": "CPU Seconds Process Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "CPU load" }
   ]
  }
 ]
}